# Generated by Django 2.0 on 2017-12-28 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbook_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenerecording',
            name='scene',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='bbook_backend.Scene'),
        ),
    ]
